version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
    volumes: 
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  dbdata:
